# NumPy
1. numpy is python's package for doing math that is more advanced than +-*
2. Has array and matrix data types. unlike lists, the values on it should be of single datatype

In [1]:
import numpy as np

In [4]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [10]:
#numpy has arrays by converting lists
vector = np.array([1,2,3])
print(vector)
matrix = np.array([[5,10,15],[2,4,6],[3,6,9]])
print('')
print(matrix)
print('')
#Transpose
print(matrix.T)

[1 2 3]

[[ 5 10 15]
 [ 2  4  6]
 [ 3  6  9]]

[[ 5  2  3]
 [10  4  6]
 [15  6  9]]


In [14]:
#one of the other multiple ways to create np array
vector2 = np.arange(0,15)
print(vector2)
print('')
vector3 = np.arange(3,21,6)
print(vector3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [18]:
#linspace start and end points in linspace that are both inclusive
#linear space - equally spaced vector. 0 and 5 are start and end. 10 is number of equal points
#reshape - returns matrix from vector. 5 rows and 2 columns
vector4 = np.linspace(0,5,10)
print(vector4)
print('')
print(vector4.reshape(5,2))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [20]:
# zeros/one/eye - create matrix of all zeros/ones/identity matrix(all zero except center diagonal)
matrix2 = np.zeros([5,3])
print(matrix2)
print('')
matrix3 = np.ones((3,5))
print(matrix3)
print('')
matrix4 = np.eye(5)
print(matrix4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
# +*-/ of arrays is possible if they are the right size. Applies artihmetic to each 
vector5 = np.arange(1,6)
vector6 = np.arange(3,8)
print(vector5)
print(vector6)
print(vector5 + vector6)
print(1/vector5)
print(np.sqrt(vector6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [22]:
print(matrix)
print(vector)
product = np.matmul(matrix, vector)
print(product)

[[ 5 10 15]
 [ 2  4  6]
 [ 3  6  9]]
[1 2 3]
[70 28 42]


In [34]:
linearmatrix=np.array([[1,2,1],[4,5,9],[1,8,9]])
print(np.linalg.solve(linearmatrix, product))
print('')
print(np.linalg.inv(linearmatrix))

[ 30.07407407  34.74074074 -29.55555556]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [37]:
#unique values in array
#notice that number 6 is converted to string
vector7 = np.array(['blue', 'red', 'orange', 'purple', 'purple', 'orange', 'Red', 6])
print(vector7)
print(np.unique(vector7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [38]:
#generate samples of random variables
rand_mat = np.random.rand(5,5) #uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) #standard normal random variable
print('')
print(rand_mat2)

[[0.26990495 0.82574233 0.10671751 0.66046762 0.7107079 ]
 [0.45498645 0.57744203 0.22775362 0.72449612 0.13602606]
 [0.02797984 0.37109638 0.21813948 0.33700637 0.60077186]
 [0.68877032 0.80654885 0.81877004 0.47480766 0.08678287]
 [0.22501548 0.14324622 0.7808627  0.49422075 0.37686959]]

[[ 0.29289928 -0.65707858  2.8147462   2.11144527 -0.83602536]
 [-0.41283374 -0.26340239 -1.65699961  1.13664235 -0.17446923]
 [ 0.45985522  0.58160625 -1.87215191 -0.27606812  1.66126186]
 [ 0.50726945  0.67539719 -0.46635358  0.61288174 -0.23104628]
 [ 1.35358611  1.61925496 -0.25107291  0.84917032 -0.2824914 ]
 [-0.16630086 -1.33349295 -0.05316999 -0.15537382  0.22452093]
 [ 0.25495738 -1.47052106 -0.65087103  0.53271502 -0.65935223]
 [ 0.24217974 -1.11831406  1.33132319  1.65044187 -0.74305576]
 [ 0.97747325  0.46091597  0.91904357  0.48345986 -0.14635308]
 [ 0.83578033  1.34597125  0.8000341  -0.24330497 -0.68694396]]


In [39]:
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.4458053204259469
0.9701805989371288


In [41]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.02797983712693064
2.814746203200426


## Accessing arrays and matrices

In [43]:
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.05761441  0.54595174 -0.52512905 -1.32408726  0.96657899 -0.99409671
  2.58767496  0.70937022 -0.91303637  0.32398355  0.45849734  1.29256909
  0.26872895  0.55510626 -0.08325118 -0.13201308  0.90914252 -1.52787478
  0.04079757]
2.58767496397755


In [47]:
#access multiple items in array
print(rand_vec[4:9])

[ 0.96657899 -0.99409671  2.58767496  0.70937022 -0.91303637]


In [57]:
#access non consequtive entries using np.arange
print(rand_vec[np.array([0,3,6,9,12])])
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])
      

[ 0.05761441 -1.32408726  2.58767496  0.32398355  0.26872895]
[ 0  3  6  9 12]
[ 0.05761441 -1.32408726  2.58767496  0.32398355  0.26872895]


In [59]:
#accessing from matrix
print(rand_mat)
print(rand_mat[1][2]) # <- list support this 
print(rand_mat[1,2]) # <- only numpy matrix supports this


[[0.26990495 0.82574233 0.10671751 0.66046762 0.7107079 ]
 [0.45498645 0.57744203 0.22775362 0.72449612 0.13602606]
 [0.02797984 0.37109638 0.21813948 0.33700637 0.60077186]
 [0.68877032 0.80654885 0.81877004 0.47480766 0.08678287]
 [0.22501548 0.14324622 0.7808627  0.49422075 0.37686959]]
0.22775361625961088
0.22775361625961088


In [61]:
print(rand_mat[0:2, 1:3]) # <- 0:2 rows 0 and 1; 1:3 cols 1 and 2

[[0.82574233 0.10671751]
 [0.57744203 0.22775362]]


## Change values

In [62]:
print(rand_vec)
rand_vec[3:5] = 4
print('')
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 0.05761441  0.54595174 -0.52512905 -1.32408726  0.96657899 -0.99409671
  2.58767496  0.70937022 -0.91303637  0.32398355  0.45849734  1.29256909
  0.26872895  0.55510626 -0.08325118 -0.13201308  0.90914252 -1.52787478
  0.04079757]


[ 0.05761441  0.54595174 -0.52512905  1.          2.         -0.99409671
  2.58767496  0.70937022 -0.91303637  0.32398355  0.45849734  1.29256909
  0.26872895  0.55510626 -0.08325118 -0.13201308  0.90914252 -1.52787478
  0.04079757]


In [63]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.26990495 0.82574233 0.10671751 0.66046762 0.7107079 ]
 [0.45498645 0.57744203 0.22775362 0.72449612 0.13602606]
 [0.02797984 0.37109638 0.21813948 0.33700637 0.60077186]
 [0.68877032 0.80654885 0.81877004 0.47480766 0.08678287]
 [0.22501548 0.14324622 0.7808627  0.49422075 0.37686959]]

[[0.26990495 0.82574233 0.10671751 0.66046762 0.7107079 ]
 [0.45498645 0.57744203 0.22775362 0.         0.        ]
 [0.02797984 0.37109638 0.21813948 0.         0.        ]
 [0.68877032 0.80654885 0.81877004 0.47480766 0.08678287]
 [0.22501548 0.14324622 0.7808627  0.49422075 0.37686959]]


In [64]:
# same as list; if not cloned, will change values of the source arrays/matrices
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:]=3
print(sub_mat)

[[0.26990495 0.82574233 0.10671751]
 [0.45498645 0.57744203 0.22775362]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [66]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)

[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.66046762 0.7107079 ]
 [3.         3.         3.         0.         0.        ]
 [0.02797984 0.37109638 0.21813948 0.         0.        ]
 [0.68877032 0.80654885 0.81877004 0.47480766 0.08678287]
 [0.22501548 0.14324622 0.7808627  0.49422075 0.37686959]]


## Access entries with logical expression 

In [67]:
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0]) # <- Access values that are greater than 0

[-0.38602967  0.92131699  0.37349212 -0.14995232  0.45825477  1.52526731
 -0.16581949 -0.37876257  0.421361   -1.58567122 -0.50904873 -0.9598055
  0.5327255   0.37842655 -1.98432792]
[False  True  True False  True  True False False  True False False False
  True  True False]
[0.92131699 0.37349212 0.45825477 1.52526731 0.421361   0.5327255
 0.37842655]


In [68]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 0.29289928 -0.65707858  2.8147462   2.11144527 -0.83602536]
 [-0.41283374 -0.26340239 -1.65699961  1.13664235 -0.17446923]
 [ 0.45985522  0.58160625 -1.87215191 -0.27606812  1.66126186]
 [ 0.50726945  0.67539719 -0.46635358  0.61288174 -0.23104628]
 [ 1.35358611  1.61925496 -0.25107291  0.84917032 -0.2824914 ]
 [-0.16630086 -1.33349295 -0.05316999 -0.15537382  0.22452093]
 [ 0.25495738 -1.47052106 -0.65087103  0.53271502 -0.65935223]
 [ 0.24217974 -1.11831406  1.33132319  1.65044187 -0.74305576]
 [ 0.97747325  0.46091597  0.91904357  0.48345986 -0.14635308]
 [ 0.83578033  1.34597125  0.8000341  -0.24330497 -0.68694396]]
[0.29289928 2.8147462  2.11144527 1.13664235 0.45985522 0.58160625
 1.66126186 0.50726945 0.67539719 0.61288174 1.35358611 1.61925496
 0.84917032 0.22452093 0.25495738 0.53271502 0.24217974 1.33132319
 1.65044187 0.97747325 0.46091597 0.91904357 0.48345986 0.83578033
 1.34597125 0.8000341 ]


## Save arrays/matrices on the disk

In [69]:
np.save('saved_file_name', rand_mat2)

In [76]:
np.savez('zipped_file_name', rand_mat=rand_mat, rand_mat2=rand_mat2)

In [81]:
#load
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)
print('')
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])


[[ 0.29289928 -0.65707858  2.8147462   2.11144527 -0.83602536]
 [-0.41283374 -0.26340239 -1.65699961  1.13664235 -0.17446923]
 [ 0.45985522  0.58160625 -1.87215191 -0.27606812  1.66126186]
 [ 0.50726945  0.67539719 -0.46635358  0.61288174 -0.23104628]
 [ 1.35358611  1.61925496 -0.25107291  0.84917032 -0.2824914 ]
 [-0.16630086 -1.33349295 -0.05316999 -0.15537382  0.22452093]
 [ 0.25495738 -1.47052106 -0.65087103  0.53271502 -0.65935223]
 [ 0.24217974 -1.11831406  1.33132319  1.65044187 -0.74305576]
 [ 0.97747325  0.46091597  0.91904357  0.48345986 -0.14635308]
 [ 0.83578033  1.34597125  0.8000341  -0.24330497 -0.68694396]]


[[3.         3.         3.         0.66046762 0.7107079 ]
 [3.         3.         3.         0.         0.        ]
 [0.02797984 0.37109638 0.21813948 0.         0.        ]
 [0.68877032 0.80654885 0.81877004 0.47480766 0.08678287]
 [0.22501548 0.14324622 0.7808627  0.49422075 0.37686959]]

[[ 0.29289928 -0.65707858  2.8147462   2.11144527 -0.83602536]
 [-0.4128337

In [83]:
#save as text file
np.savetxt('text_file_name.txt', rand_mat, delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt', delimiter=',')
print(rand_mat_txt)

[[3.         3.         3.         0.66046762 0.7107079 ]
 [3.         3.         3.         0.         0.        ]
 [0.02797984 0.37109638 0.21813948 0.         0.        ]
 [0.68877032 0.80654885 0.81877004 0.47480766 0.08678287]
 [0.22501548 0.14324622 0.7808627  0.49422075 0.37686959]]
